name: Java CI/CD with Docker, ECR, Helm, and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Java app with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
        docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DOCKER_IMAGE_NAME }}:latest

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DOCKER_IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install kubectl
      uses: azure/kubectl@v1.1.0

    - name: Configure kubectl
      run: echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > ~/.kube/config

    - name: Deploy Helm chart to EKS
      run: |
        helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} path/to/your/helm/chart -f path/to/your/values.yaml
