name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: your-dockerhub-username/your-image-name

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: >
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .
        
    - name: Tag Docker image
      run: |
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:latest
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest
