Define Secrets in Repository Settings:
Go to your repository on GitHub.
Click on "Settings" and then "Secrets".
Click on "New repository secret" and define a secret name and value.

Access Secrets in Workflow:
You can access secrets in your workflow by using the secrets context.
Secrets are exposed as environment variables in your workflow.

---
name: Use Secrets Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Secret
      run: echo "My secret value is ${{ secrets.MY_SECRET }}"

---
name: SSH Login Example

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH client
      run: sudo apt-get install openssh-client
      
    - name: Log in to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} username@ec2-instance-ip-address 'echo "Logged in successfully"'

