name: Java-SelfHosted CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Choose the appropriate Java version from your pom.xml
          distribution: 'adopt' # Specify the Linux distribution (e.g., 'adopt', 'zulu')

      - name: Debug
        run: |
          pwd
          ls -l

      - name: Build and Test
        run: |
          cd $GITHUB_WORKSPACE # Navigate to your project directory
          mvn clean install