name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm install

      - name: Build
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm run build

  deploy:
      runs-on: ubuntu-latest
      needs: build # Ensure the build job is completed before deploying

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: main # Specify the branch to be checked out