name: Nodejs CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Debug
        run: |
          pwd
          ls -l

      - name: Install dependencies
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm run build
