# name: Nodejs CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Debug
#         run: |
#           pwd
#           ls -l

#       - name: Install dependencies
#         run: |
#           cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
#           npm install

#       - name: Build
#         run: |
#           cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
#           npm run build

#       - name: Deploy using ssh
#         uses: actions/checkout@v2
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           port: 22
#           script: |
#             git pull origin main
#             git status
#             npm install --only=prod
#             npm install pm2 -g
#             npm audit fix --force
#             pm2 start index.js

name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm install

      - name: Build
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm run build

      - name: Deploy to Server
        run: |
          echo "$YOUR-SSH-KEY" > ssh_key
          chmod 600 ssh_key
          echo -e "Host 54.236.235.192\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          scp -i ssh_key -r ./dist/* root@54.236.235.192:/opt/
          ssh -i ssh_key root@54.236.235.192 'cd /opt && npm install && pm2 restart simple-nodejs-app'
        env:
          YOUR-SSH-KEY: ${{ secrets.PRIVATE_KEY }}

