name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd /home/ubuntu/actions-runner/nodejs_work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm install

      - name: Build
        run: |
          cd /home/ubuntu/actions-runner/nodejs_work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm run build

  deploy:
    runs-on: self-hosted
    needs: build # Ensure the build job is completed before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main # Specify the branch to be checked out
      
      - name: Verify current directory
        run: |
          pwd
          ls

      - name: List files in the directory
        run: ls /home/ubuntu/actions-runner/nodejs_work/devops-githubactions/devops-githubactions/node-webapp-githubactions

      - name: Deploy to Server
        run: |
          cd /home/ubuntu/actions-runner/nodejs_work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          if pm2 restart simple-nodejs-app; then
            echo "Application restarted successfully."
          else
            echo "Failed to restart the application."
            exit 1
          fi