name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm install

      - name: Build
        run: |
          cd /home/runner/work/devops-githubactions/devops-githubactions/node-webapp-githubactions
          npm run build

  deploy:
      runs-on: ubuntu-latest
      needs: build # Ensure the build job is completed before deploying

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: main # Specify the branch to be checked out
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Create the destination directory in /opt
            mkdir -p /opt/your-app
            
            # Navigate to the destination directory
            cd /opt/your-app
            
            # Pull the latest changes from the Git repository (source-less deployment)
            git pull origin main
            
            # Use PM2 to restart the application (assuming you've already built and bundled it)
            sudo pm2 stop ./dist/index.js
            sudo pm2 start ./dist/index.js
